version: '3.9'

services:
  web:
    container_name: my-awesome-app-crm-prod
    build: 
      context: ./
      dockerfile: ./Dockerfile
    ports: 
      - '8080:80'
      - '80:80'
    volumes: 
      - ./:/app 
      - ./node_modules:/app/node_modules
